CREATE TABLE IF NOT EXISTS `pay_app` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用编号',
  `app_key` varchar(64) NOT NULL COMMENT '应用标识',
  `name` varchar(64) NOT NULL COMMENT '应用名',
  `status` tinyint NOT NULL COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `order_notify_url` varchar(1024) NOT NULL COMMENT '支付回调地址',
  `refund_notify_url` varchar(1024) NOT NULL COMMENT '退款回调地址',
  `transfer_notify_url` varchar(1024) DEFAULT NULL COMMENT '转账回调地址',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_app_app_key` (`app_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付应用';

CREATE TABLE IF NOT EXISTS `pay_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '渠道编号',
  `code` varchar(32) NOT NULL COMMENT '渠道编码',
  `status` tinyint NOT NULL COMMENT '状态',
  `fee_rate` double NOT NULL DEFAULT 0 COMMENT '费率',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `config` longtext NOT NULL COMMENT '渠道配置',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_channel_app_code` (`app_id`,`code`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付渠道';

CREATE TABLE IF NOT EXISTS `pay_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '支付订单编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道编号',
  `channel_code` varchar(32) DEFAULT NULL COMMENT '渠道编码',
  `merchant_order_id` varchar(64) NOT NULL COMMENT '商户订单号',
  `subject` varchar(32) NOT NULL COMMENT '商品标题',
  `body` varchar(128) NOT NULL COMMENT '商品描述',
  `notify_url` varchar(1024) NOT NULL COMMENT '异步通知地址',
  `price` bigint NOT NULL COMMENT '支付金额(分)',
  `channel_fee_rate` double DEFAULT 0 COMMENT '渠道费率',
  `channel_fee_price` bigint DEFAULT 0 COMMENT '渠道手续费(分)',
  `status` tinyint NOT NULL COMMENT '状态',
  `user_ip` varchar(50) NOT NULL COMMENT '用户 IP',
  `user_id` bigint DEFAULT NULL COMMENT '用户编号',
  `user_type` tinyint DEFAULT NULL COMMENT '用户类型',
  `expire_time` datetime NOT NULL COMMENT '过期时间',
  `success_time` datetime DEFAULT NULL COMMENT '支付成功时间',
  `extension_id` bigint DEFAULT NULL COMMENT '成功扩展单编号',
  `no` varchar(64) DEFAULT NULL COMMENT '成功扩展单号',
  `refund_price` bigint NOT NULL DEFAULT 0 COMMENT '退款金额(分)',
  `channel_user_id` varchar(255) DEFAULT NULL COMMENT '渠道用户编号',
  `channel_order_no` varchar(64) DEFAULT NULL COMMENT '渠道订单号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_order_app_merchant` (`app_id`,`merchant_order_id`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付订单';

CREATE TABLE IF NOT EXISTS `pay_order_extension` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单扩展编号',
  `no` varchar(64) NOT NULL COMMENT '外部订单号',
  `order_id` bigint NOT NULL COMMENT '支付订单编号',
  `channel_id` bigint NOT NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NOT NULL COMMENT '渠道编码',
  `user_ip` varchar(50) DEFAULT NULL COMMENT '用户 IP',
  `status` tinyint NOT NULL COMMENT '状态',
  `channel_extras` longtext DEFAULT NULL COMMENT '渠道扩展参数',
  `channel_error_code` varchar(64) DEFAULT NULL COMMENT '渠道错误码',
  `channel_error_msg` varchar(64) DEFAULT NULL COMMENT '渠道错误消息',
  `channel_notify_data` longtext DEFAULT NULL COMMENT '渠道通知原文',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_order_extension_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付订单扩展';

CREATE TABLE IF NOT EXISTS `pay_refund` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '退款编号',
  `no` varchar(64) NOT NULL COMMENT '退款单号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `channel_id` bigint NOT NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NOT NULL COMMENT '渠道编码',
  `order_id` bigint NOT NULL COMMENT '支付订单编号',
  `order_no` varchar(64) NOT NULL COMMENT '支付单号',
  `merchant_order_id` varchar(64) NOT NULL COMMENT '商户订单号',
  `merchant_refund_id` varchar(64) NOT NULL COMMENT '商户退款单号',
  `notify_url` varchar(1024) NOT NULL COMMENT '退款通知地址',
  `status` tinyint NOT NULL COMMENT '状态',
  `pay_price` bigint NOT NULL COMMENT '原支付金额(分)',
  `refund_price` bigint NOT NULL COMMENT '退款金额(分)',
  `reason` varchar(256) NOT NULL COMMENT '退款原因',
  `user_ip` varchar(50) DEFAULT NULL COMMENT '用户 IP',
  `user_id` bigint DEFAULT NULL COMMENT '用户编号',
  `user_type` tinyint DEFAULT NULL COMMENT '用户类型',
  `channel_order_no` varchar(64) NOT NULL COMMENT '渠道订单号',
  `channel_refund_no` varchar(64) DEFAULT NULL COMMENT '渠道退款号',
  `success_time` datetime DEFAULT NULL COMMENT '成功时间',
  `channel_error_code` varchar(128) DEFAULT NULL COMMENT '渠道错误码',
  `channel_error_msg` varchar(256) DEFAULT NULL COMMENT '渠道错误信息',
  `channel_notify_data` longtext DEFAULT NULL COMMENT '渠道通知原文',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款订单';

CREATE TABLE IF NOT EXISTS `pay_notify_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '通知任务编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `type` tinyint NOT NULL COMMENT '通知类型',
  `data_id` bigint NOT NULL COMMENT '业务数据编号',
  `merchant_order_id` varchar(64) DEFAULT NULL COMMENT '商户订单号',
  `merchant_refund_id` varchar(64) DEFAULT NULL COMMENT '商户退款号',
  `merchant_transfer_id` varchar(64) DEFAULT NULL COMMENT '商户转账号',
  `status` tinyint NOT NULL COMMENT '通知状态',
  `next_notify_time` datetime DEFAULT NULL COMMENT '下次通知时间',
  `last_execute_time` datetime DEFAULT NULL COMMENT '上次执行时间',
  `notify_times` int NOT NULL COMMENT '通知次数',
  `max_notify_times` int NOT NULL COMMENT '最大通知次数',
  `notify_url` varchar(1024) NOT NULL COMMENT '通知地址',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付通知任务';

CREATE TABLE IF NOT EXISTS `pay_notify_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '通知日志编号',
  `task_id` bigint NOT NULL COMMENT '通知任务编号',
  `notify_times` int NOT NULL COMMENT '第几次通知',
  `response` varchar(1024) NOT NULL COMMENT 'HTTP 响应',
  `status` tinyint NOT NULL COMMENT '通知状态',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付通知日志';

CREATE TABLE IF NOT EXISTS `pay_transfer` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '转账编号',
  `no` varchar(64) NOT NULL COMMENT '转账单号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `channel_id` bigint NOT NULL COMMENT '渠道编号',
  `channel_code` varchar(32) NOT NULL COMMENT '渠道编码',
  `user_id` bigint DEFAULT NULL COMMENT '用户编号',
  `user_type` tinyint DEFAULT NULL COMMENT '用户类型',
  `merchant_transfer_id` varchar(64) NOT NULL COMMENT '商户转账号',
  `price` bigint NOT NULL COMMENT '金额(分)',
  `subject` varchar(256) NOT NULL COMMENT '转账标题',
  `user_account` varchar(256) NOT NULL COMMENT '收款账号',
  `user_name` varchar(64) DEFAULT NULL COMMENT '收款人姓名',
  `status` tinyint NOT NULL COMMENT '状态',
  `notify_url` varchar(1024) DEFAULT NULL COMMENT '通知地址',
  `channel_transfer_no` varchar(64) DEFAULT NULL COMMENT '渠道转账单号',
  `success_time` datetime DEFAULT NULL COMMENT '成功时间',
  `channel_error_code` varchar(128) DEFAULT NULL COMMENT '渠道错误码',
  `channel_error_msg` varchar(256) DEFAULT NULL COMMENT '渠道错误信息',
  `channel_notify_data` longtext DEFAULT NULL COMMENT '渠道通知原文',
  `channel_extras` longtext DEFAULT NULL COMMENT '渠道扩展参数',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='转账单';
